/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./src/components/layout/AppHeader.vue')['default']
    ConfirmDialog: typeof import('./src/components/modals/ConfirmDialog.vue')['default']
    MetricsHUD: typeof import('./src/components/metrics/MetricsHUD.vue')['default']
    PinModal: typeof import('./src/components/modals/PinModal.vue')['default']
    RecordFormModal: typeof import('./src/components/modals/RecordFormModal.vue')['default']
    SearchAndFilter: typeof import('./src/components/layout/SearchAndFilter.vue')['default']
    TableHeader: typeof import('./src/components/table/TableHeader.vue')['default']
    UApp: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UBadge: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Badge.vue')['default']
    UButton: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UCard: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Card.vue')['default']
    UInput: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Input.vue')['default']
    UModal: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Modal.vue')['default']
    USwitch: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Switch.vue')['default']
    VirtualCard: typeof import('./src/components/mobile/VirtualCard.vue')['default']
    VirtualCardList: typeof import('./src/components/mobile/VirtualCardList.vue')['default']
    VirtualDataTable: typeof import('./src/components/table/VirtualDataTable.vue')['default']
    VirtualRow: typeof import('./src/components/table/VirtualRow.vue')['default']
  }
}
